### ISSUE TITLE
Sippy b2bua rtpengine compatibility

### ISSUE THREAD

**Issue by mateuszbbb** [sippy/b2bua#29]
Trying to replace rtpproxy with more modern sipwise/rtpengine

According to their documentation: 
rtpengine can be used as a drop-in replacement for any other compatible RTP proxy

But it seems that Sippy is sending some commands, that are not understood by rtpengine

Any fixes possible? Or maybe suggestions how to get b2bua working with rtpengine?

**Comment by sobomax** [comment]
We are not rtp engine users ourselves, so I don't think we can help you with this any time soon. Patch would be welcome if course, either on our end or at theirs. The interaction with the media relay is well abstracted under Rtp_proxy_session.py, so it should not be too difficult to modify to make offending commands/options optional.
