### ISSUE TITLE
[Question] SipTransactionManager handles UAC ACKs vs RFC6026

### ISSUE THREAD

**Issue by space88man** [sippy/b2bua#32]
SipTransactionManager transparently handles client ACK to 200 OK and retransmissions of 200 OK in `incomingResponse()`.

RFC6026 seems to indicate that the handling of ACK to 200 OK should be done by the TU. 

My question: is this a deliberate design decision  in b2bua to put creation of ACK in SipTransactionManager rather than leaving it to the business logic? (Maybe the UacStateRinging->UaStateConnected should be responsible for sending ACK?).

I can see that the current behaviour simplifies business logic as the ACK is handled at the lower level

RFC6026 Page 12:

> When a 2xx response is received while in either the "Calling" or
      "Proceeding" states, the client transaction MUST transition to the
      "Accepted" state, and Timer M MUST be started with a value of
      64*T1.  The 2xx response MUST be passed up to the TU.  The client
      transaction MUST NOT generate an ACK to the 2xx response -- its
      handling is delegated to the TU.

(In b2bua  "Calling" == TRYING "Proceeding" == RINGING)

There is also a UACK state and `t.uack` property, is this meant for scripts that want to handle ACK generation  on their own?

**Comment by sobomax** [comment]
Hi, yes, this is correct. The point here is that once upper layer has dispatched 200 OK there is not much to do, unless retransmits have lapsed. At the same time it makes upper-level FSM so much simpler. The uack is for cases when tighter control is needed (i.e. some tests we have here https://github.com/sippy/voiptests/blob/RFC8760/test_cases/reinv_bad_ack.py#L43, also later-offer support code).

Recently we've also entertained the idea of delaying the ACK until the upstream ACK has been received, but that seems to be a somewhat questionable proposition, as with few B2B elements in the call flow that would cause intermediary B2BUAs spinning their wheels sending retransmits to each other as soon as the total delay gets into 500ms range. So we decided to keep the current approach.  Hope it explains! :)
